package arrow;

public enum Enchantment
{
	ARROW_INFINITE, ARROW_KNOCKBACK, ARROW_DAMAGE, WATER_WORKER, SILK_TOUCH, PROTECTION_PROJECTILE, PROTECTION_FIRE, PROTECTION_FALL, PROTECTION_EXPLOSIONS, PROTECTION_ENVIRONMENTAL, OXYGEN, LOOT_BONUS_MOBS, LOOT_BONUS_BLOCKS, KNOCKBACK, FIRE_ASPECT, DURABILITY, DIG_SPEED, DAMAGE_UNDEAD, DAMAGE_ARTHROPODS, DAMAGE_ALL, THORNS
}
